#!/bin/bash

file_name="korean"
input_file="${file_name}.txt"
mkdir -p ${file_name}

#sox -t mp3 ${file_name}.mp3 -t wav -r 8000 -c 1 ${file_name}.wav
sox -t mp3 ${file_name}.mp3 -t wav -r 44100 -c 2 ${file_name}.wav


sox -V3 ${file_name}.wav ${file_name}/.wav silence 0 1 2.000 0.1% : newfile : restart

count=001
while read -r line; do

mv "${file_name}"/"${count}.wav" "${file_name}"/"$line".wav
sox "${file_name}"/"$line".wav "${file_name}"/"${line}_slow.wav" tempo 0.65

lame "${file_name}"/"$line".wav "${file_name}"/"$line".mp3
rm -f "${file_name}"/"$line".wav
lame "${file_name}"/"${line}_slow".wav "${file_name}"/"${line}_slow".mp3
rm -f "${file_name}"/"${line}_slow".wav
#count=`printf '%03d' $((++count))`
count=`echo "$count + 1" | bc`
count=`printf '%03d' "$count"`

done < "$input_file"

